# Generated by Django 5.1.6 on 2025-03-18 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the blog post.', max_length=200)),
                ('content', models.TextField(help_text='Content of the blog post.')),
                ('published_date', models.DateTimeField(auto_now_add=True, help_text='Date and time the post was published.')),
                ('author', models.ForeignKey(help_text='Author of the blog post.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
